export default [
  {
    id: 1,
    name: "shoe-24",
    type: "shoe",
    description: "very quality louvition",
    price: 234,
    quantity: 5,
    address: "123 Main Street",
  },
  {
    id: 2,
    name: "shirt-10",
    type: "shirt",
    description: "comfortable cotton fabric",
    price: 45,
    quantity: 10,
    address: "456 Elm Avenue",
  },
  {
    id: 3,
    name: "pants-32",
    type: "pants",
    description: "stylish slim fit design",
    price: 79,
    quantity: 8,
    address: "789 Oak Boulevard",
  },
  {
    id: 4,
    name: "hat-15",
    type: "hat",
    description: "adjustable strap for a perfect fit",
    price: 30,
    quantity: 15,
    address: "1011 Pine Lane",
  },
  {
    id: 5,
    name: "dress-08",
    type: "dress",
    description: "elegant evening wear",
    price: 150,
    quantity: 3,
    address: "1313 Cedar Street",
  },
  {
    id: 6,
    name: "watch-03",
    type: "watch",
    description: "water-resistant, stainless steel",
    price: 199,
    quantity: 7,
    address: "1515 Maple Avenue",
  },
  {
    id: 7,
    name: "bag-20",
    type: "bag",
    description: "spacious compartments, durable material",
    price: 75,
    quantity: 12,
    address: "1717 Oak Street",
  },
  {
    id: 8,
    name: "sunglasses-05",
    type: "sunglasses",
    description: "UV protection, polarized lenses",
    price: 120,
    quantity: 9,
    address: "1919 Elm Lane",
  },
  {
    id: 9,
    name: "jacket-12",
    type: "jacket",
    description: "warm and stylish winter wear",
    price: 180,
    quantity: 6,
    address: "2121 Pine Avenue",
  },
  {
    id: 10,
    name: "scarf-07",
    type: "scarf",
    description: "soft and cozy knit fabric",
    price: 25,
    quantity: 20,
    address: "2323 Cedar Lane",
  },
  {
    id: 6,
    name: "watch-03",
    type: "watch",
    description: "water-resistant, stainless steel",
    price: 199,
    quantity: 7,
    address: "1515 Maple Avenue",
  },
  {
    id: 7,
    name: "bag-20",
    type: "bag",
    description: "spacious compartments, durable material",
    price: 75,
    quantity: 12,
    address: "1717 Oak Street",
  },
  {
    id: 8,
    name: "sunglasses-05",
    type: "sunglasses",
    description: "UV protection, polarized lenses",
    price: 120,
    quantity: 9,
    address: "1919 Elm Lane",
  },
  {
    id: 9,
    name: "jacket-12",
    type: "jacket",
    description: "warm and stylish winter wear",
    price: 180,
    quantity: 6,
    address: "2121 Pine Avenue",
  },
  {
    id: 10,
    name: "scarf-07",
    type: "scarf",
    description: "soft and cozy knit fabric",
    price: 25,
    quantity: 20,
    address: "2323 Cedar Lane",
  },
];
